name: Test Runner (Space)

on:
  workflow_dispatch:

jobs:
  test-space:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test Space
        shell: powershell
        run: |
          Get-CimInstance Win32_LogicalDisk -Filter "(DriveType=3) and (DeviceID='C:' or DeviceID='D:')" |
            Select-Object @{
              Name = 'DeviceID';      Expression = { $_.DeviceID }
            },
            @{
              Name = 'VolumeName';          Expression = { $_.VolumeName }
            },
            @{
              Name = 'Size(GB)';    Expression = { [int][math]::Round($_.Size / 1GB) }
            },
            @{
              Name = 'Used(GB)';      Expression = { [int][math]::Round(($_.Size - $_.FreeSpace) / 1GB) }
            },
            @{
              Name = 'Free(GB)';      Expression = { [int][math]::Round($_.FreeSpace / 1GB) }
            },
            @{
              Name = 'utilization_rate%';       Expression = { [math]::Round((($_.Size - $_.FreeSpace) / $_.Size) * 100, 1) }
            } |
            Format-Table -AutoSize
      - name: test big Files
        run: |
          fsutil file createnew D:\testfile.dat 10737418240
          if exist D:\testfile.dat (
            echo File created successfully.
          ) else (
            echo Failed to create file.
            exit /b 1
          )
          fsutil file createnew D:\testfile2.dat 20737418240
          if exist D:\testfile2.dat (
            echo File created successfully.
          ) else (
            echo Failed to create file.
            exit /b 1
          )
          fsutil file createnew D:\testfile3.dat 30737418240
          if exist D:\testfile3.dat (
            echo File created successfully.
          ) else (
            echo Failed to create file.
            exit /b 1
          )