name: Test Runner (Space)

on:
  workflow_dispatch:

jobs:
  test-space:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test Space
        shell: powershell
        run: |
          Get-CimInstance Win32_LogicalDisk -Filter "(DriveType=3) and (DeviceID='C:' or DeviceID='D:')" |
            Select-Object @{
              Name = 'DeviceID';      Expression = { $_.DeviceID }
            },
            @{
              Name = '卷标';          Expression = { $_.VolumeName }
            },
            @{
              Name = '总容量(GB)';    Expression = { [int][math]::Round($_.Size / 1GB) }
            },
            @{
              Name = '已用(GB)';      Expression = { [int][math]::Round(($_.Size - $_.FreeSpace) / 1GB) }
            },
            @{
              Name = '剩余(GB)';      Expression = { [int][math]::Round($_.FreeSpace / 1GB) }
            },
            @{
              Name = '使用率%';       Expression = { [math]::Round((($_.Size - $_.FreeSpace) / $_.Size) * 100, 1) }
            } |
            Format-Table -AutoSize